RockTunnel_B1F_Text_SofiaIntro::
    .string "Do you know how you can avoid\n"
    .string "getting lost in the mountains?\p"
    .string "You can bend twigs as trail\n"
    .string "markers.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Ohhh!\n"
    .string "I did my best!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "I want to go home!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Can you beat my power?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Oops!\n"
    .string "Outmuscled!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "I go for power because I hate\n"
    .string "thinking.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "You have a POKéDEX?\n"
    .string "I want one, too.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Shoot!\n"
    .string "I am so jealous!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "When you finish your POKéDEX,\n"
    .string "can I have it?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Um… Do you know about POKéMON\n"
    .string "cosplay?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Well, that's that.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "POKéMON cosplay is dressing up as\n"
    .string "POKéMON for fun.\p"
    .string "CLEFAIRY is a favorite.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "My POKéMON techniques will leave\n"
    .string "you crying!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "I give!\n"
    .string "You're a better technician!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "In mountains, you'll often find\n"
    .string "ROCK-type POKéMON.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Hey! I want to sleep on the couch\n"
    .string "How dare you interrupt my rest?!\n"
    .string "Behold, my team of brown pokemon!\n"
    .string "Sneeze$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Oops.\n"
    .string "I am still sleeping!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Did you know that your Dad made \n"
    .string "this game? This game is originally \n"
    .string "based on Pokemon Firered!\n"
    .string "He placed a lot of special characters\n"
    .string "in the world for you to find.\n"
    .string "You know many of them, and some\n"
    .string "you never got the chance to meet.\n"
    .string "I, for instance, am based one of your dogs.\n"
    .string "I loved to sleep on the couch!\n"
    .string "Kevin and Phyllis outside are also based on\n"
    .string "your dogs.\n"
    .string "Cool, right?\n"
    .string "Sneeze$"

RockTunnel_B1F_Text_EricIntro::
    .string "Hit me with your best shot!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Fired away!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "I'll raise my POKéMON to beat\n"
    .string "yours, kid.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "I draw illustrations of POKéMON\n"
    .string "when I'm home.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Whew…\n"
    .string "I'm exhausted…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "I'm an artist, not a fighter.\n"
    .string "I'll go home to draw.$"

